categories: [Visualization]
description: A tool to create a UCSC track hub
name: hubarchivecreator
owner: rmarenco
remote_repository_url: https://github.com/goeckslab/hub-archive-creator
exclude:
  - hubaDataType/datatypes_conf.xml
  - hubaDataType/README.md
  - hubaDataType/trackhub.xml
  - hubaDataType/tracks_partial.py
  - tool_test_output.html
  - tool_test_output.json
  - README.md
